version: '4.0'

services:
  app:
    image: python:3.12.6-bullseye
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env 
    depends_on:
      - scraping
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      /bin/bash -c "
      pip install --no-cache-dir -r requirements.txt &&
      streamlit run /app/docstoteles/Home.py
      "
    networks:
      - asimov
  
  scraping:
    image: 
    container_name: scraping
    env_file:
      - .env 
    command: >
      /bin/bash -c "
      "
    networks:
      - asimov

networks:
  asimov:
    external: true
